#' Strip the leading "uuid:" from a UUID hash.
#'
#' \lifecycle{stable}
#'
#' @param uuid A string which may contain any number of "uuid:"
#' @return The string with every occurrence of "uuid:" deleted.
#' @family utilities
#' @export
#' @examples
#' strip_uuid("uuid:1234")
#' strip_uuid("uuid:d3bcefea-32a8-4dbc-80ca-4ecb0678e2b0")
strip_uuid <- function(uuid) {
  uuid %>% stringr::str_replace_all(., pattern = "uuid:", replacement = "")
}

#' Prepend a leading "uuid:" to any string, e.g. an md5 hash.
#'
#' \lifecycle{stable}
#'
#' @param md5hash A string, e.g. an md5 hash.
#' @return The string with a prepended "uuid:"
#' @family utilities
#' @export
#' prepend_uuid("1234")
#' prepend_uuid("d3bcefea-32a8-4dbc-80ca-4ecb0678e2b0")
prepend_uuid <- function(md5hash) {
  glue::glue("uuid:{md5hash}") %>% as.character(.)
}

#' Build the download URL for one or many submission UUIDs and filenames.
#'
#' \lifecycle{stable}
#'
#' This is a helper function used by \code{\link{attachment_get}}.
#' This function is vectorised and accepts single values or vectors for uuid and
#' fn.
#'
#' @param uuid The UUID of one form submission, or a vector of UUIDs.
#' @param fn The attachment filename, as per ODK form submission, or a vector of
#'           attachment filenames.
#' @template param-pid
#' @template param-fid
#' @template param-url
#' @return The inferred download URL.
#' @family odata-api
#' @examples
#' ruODK:::attachment_url("uuid:d3bcefea-32a8-4dbc-80ca-4ecb0678e2b0",
#'   "filename.jpg",
#'   pid = 1, fid = "form1",
#'   url = "https://sandbox.central.opendatakit.com"
#' )
attachment_url <- function(uuid,
                           fn,
                           pid = get_default_pid(),
                           fid = get_default_fid(),
                           url = get_default_url()) {
  glue::glue(
    "{url}/v1/projects/{pid}/forms/{fid}/submissions/{uuid}/attachments/{fn}"
  )
}

#' Download one media attachment.
#'
#' \lifecycle{stable}
#'
#' This is a helper function used by \code{\link{attachment_get}}.
#' This function is not vectorised, but mapped by \code{\link{attachment_get}}
#' to a tibble of input parameters.
#'
#' @param pth A local file path to save the attachment to.
#' @param fn The attachment filename, as per ODK form submission. If NA, no file
#'   will be downloaded, but NA will be returned.
#' @param src The attachment's download URL, generated by
#'   \code{\link{attachment_url}}.
#' @template param-url
#' @template param-auth
#' @param verbose Whether to display debug messages or not (default).
#' @return The relative local path to the downloaded attachment or NA.
#' @family odata-api
#' @export
#' \dontrun{
#' # Step 1: Setup ruODK with OData Service URL (has url, pid, fid)
#' ruODK::ru_setup(svc="...")
#'
#' # Step 2: Construct attachment_url
#' att_url <- ruODK:::attachment_url(
#'   "uuid:d3bcefea-32a8-4dbc-80ca-4ecb0678e2b0",
#'   "filename.jpg"
#' )
#'
#' # Step 3: Get one attachment
#' local_fn <- get_one_attachment("media/filename.jpg", "filename.jpg", att_url)
#'
#' # In real life: done in bulk behind the scenes during odata_submission_get()
#' }
get_one_attachment <- function(pth,
                               fn,
                               src,
                               url = get_default_url(),
                               un = get_default_un(),
                               pw = get_default_pw(),
                               verbose = FALSE) {
  yell_if_missing(url, un, pw)
  if (fs::file_exists(pth)) {
    if (verbose == TRUE) {
      message(crayon::green(
        glue::glue(
          "{clisymbols::symbol$circle_filled} ",
          "File already downloaded, keeping \"{pth}\".\n"
        )
      ))
    }
    return(pth %>% as.character())
  }
  if (is.na(fn)) {
    if (verbose == TRUE) {
      message(crayon::green(
        glue::glue(
          "{clisymbols::symbol$circle} ",
          "Filename is NA, skipping download.\n"
        )
      ))
    }
    return(NA)
  }

  httr::GET(
    src,
    httr::authenticate(un, pw),
    httr::write_disk(pth, overwrite = TRUE)
  ) %>%
    yell_if_error(., url, un, pw)

  if (verbose == TRUE) {
    message(crayon::green(
      glue::glue(
        "{clisymbols::symbol$tick} ",
        "File saved to \"{pth}\".\n"
      )
    ))
  }


  return(pth %>% as.character())
}

#' Download attachments and return the local path.
#'
#' \lifecycle{stable}
#'
#' @details This function is vectorised and can handle either one or many
#' records.
#' Parameters submission_uuid and attachment_filename accept single or exactly
#' the same number of multiple values.
#' The other parameters are automatically repeated.
#'
#' The media attachments are downloaded into a folder given by `local_dir`:
#'
#' workdir/media/filename1.jpg
#'
#' workdir/media/filename2.jpg
#'
#' workdir/media/filename3.jpg
#'
#' @param sid One or many ODK submission UUIDs, an MD5 hash.
#' @param fn One or many ODK form attachment filenames,
#'   e.g. "1558330537199.jpg".
#' @param local_dir The local folder to save the downloaded files to,
#'   default: "media".
#' @param separate (logical) Whether to separate locally downloaded files into
#'   a subfolder named after the submission uuid within `local_dir`,
#'   default: FALSE.
#'   The defaults mirror the behaviour of \code{\link{submission_export}}, which
#'   keeps all attachment files together in a folder `media`.
#'   Enable this option if downloaded files collide on idential names. This can
#'   happen if two data collection devices by chance generate the same filename
#'   for two respective media files, e.g. `DCIM0001.jpg`.
#' @template param-pid
#' @template param-fid
#' @template param-url
#' @template param-auth
#' @template param-verbose
#' @return The relative file path for the downloaded attachment(s)
#' @family odata-api
# nolint start
#' @seealso \url{https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-form-attachments/downloading-a-form-attachment}
#' @seealso \url{https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/attachments/downloading-an-attachment}
# nolint end
#' @export
#' @examples
#' \dontrun{
#' # Step 1: Setup ruODK with OData Service URL (has url, pid, fid)
#' ruODK::ru_setup(svc = "...")
#' a_local_dir <- here::here()
#'
#' # Step 2: Get unparsed submissions
#' fresh_raw <- odata_submission_get(parse = FALSE)
#'
#' # Step 3: Get attachment field "my_photo"
#' fresh_parsed <- fresh_raw %>%
#'   odata_submission_parse() %>%
#'   dplyr::mutate(
#'     my_photo = attachment_get(id,
#'       my_photo,
#'       local_dir = a_local_dir,
#'       verbose = TRUE
#'     )
#'     # Repeat for all other attachment fields
#'   )
#' }
attachment_get <- function(sid,
                           fn,
                           local_dir = "media",
                           separate = FALSE,
                           pid = get_default_pid(),
                           fid = get_default_fid(),
                           url = get_default_url(),
                           un = get_default_un(),
                           pw = get_default_pw(),
                           verbose = FALSE) {
  yell_if_missing(url, un, pw, pid = pid, fid = fid)
  if (separate == TRUE) {
    dest_dir <- fs::path(local_dir, strip_uuid(sid))
  } else {
    dest_dir <- fs::path(local_dir)
  }
  if (verbose == TRUE) {
    # CMD check can't detect use of clisymbols inside glue statement
    infosymbol <- clisymbols::symbol$info

    message(crayon::cyan(
      glue::glue(
        "{clisymbols::symbol$info} ",
        "Using local directory \"{dest_dir}\".\n"
      )
    ))
  }

  fs::dir_create(dest_dir)

  tibble::tibble(
    pth = fs::path(dest_dir, fn),
    fn = fn,
    src = attachment_url(sid, fn, pid = pid, fid = fid, url = url),
    url = url,
    un = un,
    pw = pw,
    verbose = verbose
  ) %>%
    purrr::pmap(get_one_attachment) %>%
    as.character(.)
}

# Tests
# usethis::edit_file("tests/testthat/test-attachment_get.R")
