#' Build the download URL for one or many submission UUIDs and filenames.
#'
#' This is a helper function used by `get_attachment`.
#' This function is vectorised and accepts single values or vectors for uuid and fn.
#'
#' @param data_url The OData service URL as given by ODK Central.
#' @param uuid The UUID of one form submission, or a vector of UUIDs.
#' @param fn The attachment filename, as per ODK form submission, or a vector of
#'           attachment filenames.
#' @return The inferred download URL.
attachment_url <- function(data_url, uuid, fn) {
  base_url <- stringr::str_remove_all(data_url, ".svc")
  glue::glue("{base_url}/submissions/{uuid}/attachments/{fn}")
}

#' Download one media attachment
#'
#' This is a helper function used by `get_attachment`.
#' This function is not vectorised, but mapped by `get_attachment` to a tibble
#' of input parameters.
#'
#' @param pth A local file path to save the attachment to.
#' @param fn The attachment filename, as per ODK form submission. If NA, no file
#'           will be downloaded, but NA will be returned.
#' @param src The attachment's download URL, generated by `attachment_url`.
#' @param un The ODK Central username (an email address),
#'           default: Sys.getenv("ODKC_UN").
#'           Add to your ~/.Rprofile: Sys.setenv(ODKC_UN="...@...")
#' @param pw The ODK Central password,,
#'           default: Sys.getenv("ODKC_PW").
#'           Add to your ~/.Rprofile: Sys.setenv(ODKC_PW="...")
#' @param verbose Whether to display debug messages or not (default)
#' @return The relative local path to the downloaded attachment or NA.
#' @importFrom httr GET authenticate write_disk
#' @importFrom fs file_exists
#' @importFrom rlang warn
#' @export
get_one_attachment <- function(pth, fn, src,
                               un = Sys.getenv("ODKC_UN"),
                               pw = Sys.getenv("ODKC_PW"),
                               verbose = FALSE) {
  if (fs::file_exists(pth)) {
    return(pth %>% as.character())
  }
  if (is.na(fn)) {
    rlang::warn("Filename is NA, skipping download.")
    return(NA)
  }
  httr::GET(src, httr::authenticate(un, pw), httr::write_disk(pth, overwrite = T))
  if (verbose == TRUE) message(glue::glue("Saved {pth}\n"))
  return(pth %>% as.character())
}

#' Download attachments and return the local path
#'
#' This function is vectorised and can handle either one or many records.
#' Parameters submission_uuid and attachment_filename accept single or exactly
#' the same number of multiple values.
#' The other parameters are automatically repeated.
#'
#' The media attachments are downloaded into a folder named by the submission's
#' uuid inside the given `local_dir`. E.g.:
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename1.jpg
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename2.jpg
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename3.jpg
#'
#' @param data_url The ODK Central OData url, including the ".svc"
#' @param submission_uuid One or many ODK submission UUIDs, an MD5 hash
#' @param attachment_filename One or many ODK form attachment filenames,
#'                            e.g. "1558330537199.jpg"
#' @param local_dir The local folder to save the downloaded files to,
#'                  default: "attachments"
#' @param un The ODK Central username (an email address),
#'           default: Sys.getenv("ODKC_UN").
#'           Add to your ~/.Rprofile: Sys.setenv(ODKC_UN="...@...")
#' @param pw The ODK Central password,,
#'           default: Sys.getenv("ODKC_PW").
#'           Add to your ~/.Rprofile: Sys.setenv(ODKC_PW="...")
#' @param verbose Whether to display debug messages or not (default)
#' @return The relative file path for the downloaded attachment(s)
#' @importFrom glue glue
#' @importFrom fs dir_create path
#' @importFrom httr authenticate GET write_disk
#' @importFrom purrr pmap
#' @importFrom stringr str_remove_all
#' @export
get_attachment <- function(data_url,
                           submission_uuid,
                           attachment_filename,
                           local_dir = "attachments",
                           un = Sys.getenv("ODKC_UN"),
                           pw = Sys.getenv("ODKC_PW"),
                           verbose = FALSE) {
  dest_dir <- fs::path(local_dir, submission_uuid)
  if (verbose == TRUE) message(glue::glue("Using local directory: {dest_dir}\n"))
  fs::dir_create(dest_dir)

  tibble::tibble(
    pth = fs::path(dest_dir, attachment_filename),
    fn = attachment_filename,
    src = attachment_url(data_url, submission_uuid, attachment_filename),
    un = un,
    pw = pw,
    verbose = verbose
  ) %>%
    purrr::pmap(get_one_attachment)
}
