#' Strip the leading "uuid:" from a UUID hash.
#'
#' @param uuid A string which may contain any number of "uuid:"
#' @return The string with every occurrence of "uuid:" deleted.
#' @export
#' @importFrom stringr str_replace
strip_uuid <- function(uuid) {
  . <- NULL
  uuid %>% stringr::str_replace_all(., pattern = "uuid:", replacement = "")
}

#' Prepend a leading "uuid:" to any string, e.g. an md5 hash.
#'
#' @param md5hash A string, e.g. an md5 hash.
#' @return The string with a prepended "uuid:"
#' @export
#' @importFrom glue glue
prepend_uuid <- function(md5hash) {
  . <- NULL
  glue::glue("uuid:{md5hash}") %>% as.character(.)
}

#' Build the download URL for one or many submission UUIDs and filenames.
#'
#' This is a helper function used by `get_attachment`.
#' This function is vectorised and accepts single values or vectors for uuid and
#' fn.
#'
#' @template param-pid
#' @template param-fid
#' @param uuid The UUID of one form submission, or a vector of UUIDs.
#' @param fn The attachment filename, as per ODK form submission, or a vector of
#'           attachment filenames.
#' @param url The OData URL, ending in .svc, no trailing slash.
#' @return The inferred download URL.
attachment_url <- function(pid, fid, uuid, fn,
                           url = Sys.getenv("ODKC_URL")) {
  glue::glue(
    "{url}/v1/projects/{pid}/forms/{fid}/",
    "submissions/{uuid}/attachments/{fn}"
  )
}

#' Download one media attachment
#'
#' This is a helper function used by `get_attachment`.
#' This function is not vectorised, but mapped by `get_attachment` to a tibble
#' of input parameters.
#'
#' @param pth A local file path to save the attachment to.
#' @param fn The attachment filename, as per ODK form submission. If NA, no file
#'           will be downloaded, but NA will be returned.
#' @param src The attachment's download URL, generated by `attachment_url`.
#' @template param-auth
#' @param verbose Whether to display debug messages or not (default)
#' @return The relative local path to the downloaded attachment or NA.
#' @importFrom httr GET authenticate write_disk
#' @importFrom fs file_exists
#' @export
get_one_attachment <- function(pth, fn, src,
                               url = Sys.getenv("ODKC_URL"),
                               un = Sys.getenv("ODKC_UN"),
                               pw = Sys.getenv("ODKC_PW"),
                               verbose = FALSE) {
  if (fs::file_exists(pth)) {
    if (verbose == TRUE) message(glue::glue("Keeping {pth}\n"))
    return(pth %>% as.character())
  }
  if (is.na(fn)) {
    message("Filename is NA, skipping download.")
    return(NA)
  }
  httr::GET(
    src,
    httr::authenticate(un, pw),
    httr::write_disk(pth, overwrite = TRUE)
  )
  if (verbose == TRUE) message(glue::glue("Saved {pth}\n"))
  return(pth %>% as.character())
}

#' Download attachments and return the local path
#'
#' This function is vectorised and can handle either one or many records.
#' Parameters submission_uuid and attachment_filename accept single or exactly
#' the same number of multiple values.
#' The other parameters are automatically repeated.
#'
#' The media attachments are downloaded into a folder named by the submission's
#' uuid inside the given `local_dir`. E.g.:
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename1.jpg
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename2.jpg
#'
#' workdir/attachments/uuid:xxxxxxxxxx/filename3.jpg
#'
#' @template param-pid
#' @template param-fid
#' @param submission_uuid One or many ODK submission UUIDs, an MD5 hash
#' @param attachment_filename One or many ODK form attachment filenames,
#'                            e.g. "1558330537199.jpg"
#' @param local_dir The local folder to save the downloaded files to,
#'                  default: "attachments"
#' @template param-auth
#' @param verbose Whether to display debug messages or not (default)
#' @return The relative file path for the downloaded attachment(s)
#' @importFrom glue glue
#' @importFrom fs dir_create path
#' @importFrom httr authenticate GET write_disk
#' @importFrom purrr pmap
#' @importFrom stringr str_remove_all
#' @export
get_attachment <- function(pid,
                           fid,
                           submission_uuid,
                           attachment_filename,
                           local_dir = "attachments",
                           url = Sys.getenv("ODKC_URL"),
                           un = Sys.getenv("ODKC_UN"),
                           pw = Sys.getenv("ODKC_PW"),
                           verbose = FALSE) {
  dest_dir <- fs::path(local_dir, strip_uuid(submission_uuid))
  if (verbose == TRUE) {
    message(glue::glue("Using local directory: {dest_dir}\n"))
  }
  fs::dir_create(dest_dir)

  tibble::tibble(
    pth = fs::path(dest_dir, attachment_filename),
    fn = attachment_filename,
    src = attachment_url(
      pid,
      fid,
      submission_uuid,
      attachment_filename,
      url = url
    ),
    un = un,
    pw = pw,
    verbose = verbose
  ) %>%
    purrr::pmap(get_one_attachment)
}
